name: Test
on:
  push:
    branches:
      - master
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          #run test cases file
          python ./tests/testcases.py